apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: demo-app
  labels:
    env: staging
  input:
    manifests:
      - ../kubernetes/base/deployment.yaml
      - ../kubernetes/base/service.yaml
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: WAIT
        with:
          duration: 2m
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN